spring.datasource.dashboard:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/afagoal_sys?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: root
    password: root
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxIdleTime: 1800
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60 * 60 * 1000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    #testOnBorrow: false
    #testOnReturn: false
    #poolPreparedStatements: true
    #maxPoolPreparedStatementPerConnectionSize: 20
    #filters: stat,wall,slf4j
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #useGlobalDataSourceStat: true

server:
  port: 18080