spring.datasource.dashboard:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.24.27.218:3306/afagoal_sys?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: afagoal_sys
    password: sys_oa
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxIdleTime: 1800
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60 * 60 * 1000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    #testOnBorrow: false
    #testOnReturn: false
    #poolPreparedStatements: true
    #maxPoolPreparedStatementPerConnectionSize: 20
    #filters: stat,wall,slf4j
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #useGlobalDataSourceStat: true

spring:
  thymeleaf:
    prefix: classpath:/templates/


afagoal.mail.from: 18296154779@163.com


spring.mail.host: smtp.163.com
spring.mail.port: 25
spring.mail.username: 18296154779@163.com
spring.mail.password: baocai1234
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
spring.mail.properties.mail.smtp.timeout: 25000
spring.mail.properties.mail.smtp.auth: true